apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: "/spec/url/hostname"
        value: 'admin.fintlabs.no'
    target:
      kind: Application
      name: admin-portal
