apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-admin-portal-frontend
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-admin-portal-frontend
    app.kubernetes.io/instance: fint-admin-portal-frontend_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8000
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-admin-portal-frontend-v2:latest
  env:
    - name: API_URL
      value: http://fint-admin-portal-backend:8080
  url:
    hostname: admin-beta.fintlabs.no
    basePath: /
  ingress:
    enabled: true
    middlewares:
      - fint-admin-portal-sso