name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          VITE_MOCK_CYPRESS: true
          API_URL: http://fint-admin-portal-backend:8080
        with:
          build: npm run build
          start: npm start

          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60

          browser: chrome

      - name: Start deployment
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.GITHUBACTION_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-cd
